import java.util.*;

public class SummerWorkReview
{
   public static void main(String [] args)
   {
      Scanner it=new Scanner(System.in);
   
   //Q1 how do you use the scanner to populate the following variables
      //System.out.println("Please enter your name");
      //String x=it scan.nextLine();
      //System.out.println("Hi " + x + "!");
      //System.out.println("Please enter your age: ");
      //int age = it.nextInt();
      //System.out.printLn("Please enter your height in cm: ");
      //double height=it.nextDouble();
      //System.out.println("You are " +age+ "years old and are " +height+ " cm tall");
   
      int num=723;
   //Q2
   //how do you print the hundreds column
	   //System.out.println("hundreds digit = " +num/100);
   //how do you print the 1's column
	   //System.out.println("1's digit = " +num%10);
   //System.out.println("hundreds column=" + );
    //System.out.println("ones column=" + );
   //how do you print the tens column of the original number
	   //int tens = (num/10)%10;
   //System.out.println("tens column="+num%10);
      
   // indexOf, /n, subString, null, compareTo
   
   
   //Q3 What is the output when val is printed
   
      int val=-123;
      val--;
      val--;
      val--;
   //System.out.println(val);
   
   //Q4
   //correct the code
   //int sum=-123.456;
   
   //Q5 How do you store the phrase Have a nice day in a String variable called greeting
   String greeting = "Have a nice day";
   System.out.println(greeting);

   //Q6
   //What is the output of the following lines of code?
   System.out.println(100+100); 
   //output 200
   System.out.println("s"+100+100); 
   //output s100100
   System.out.println(100+(100+100));
   //output 300
      
   //Q7 - find the true average of 3 plus 4
   
   //Q8
      int num2=5;
      num2+=10;
      num2*=3;
      num2-=5;
      //System.out.println("num2%3="+num2%3);
      
   //Q9 what is generated by the following lines of code
      double x=Math.random();
   
   //Q10 
      int total_mins=500;
      //int hours=;
      //int mins=;
      //System.out.println("500 minutes is equivalent to " +hours+ " hours and " + mins +" minutes.");
      
   //Q11 
      int totalPennies=1234;
   //if I turned these pennies into the bank, what is the maximum number of quarters I would receive?
   //how much change is left over in pennies?
   // int maxNumQuarters=
   //int numLeftOverPennies
    
    
    
   
   
   
   
   }
}